### ISSUE TITLE
The tracking speed is slow using GPU

### ISSUE THREAD

**Issue by zhengzhenxian** [tsingqguo/DSiam#3]
Thanks for your sharing code, I run your code using my GPU 'TITAN TI 1080' , but I find that the speed is quite slow, and your paper introduce that the speed >40 fps. I also set the param useGPU = true. Could you please tell how to solve the problem?  Many thanks!
1_DSiam, 1_carDark: 1/1
fps: 7.4509
1_DSiam, 2_car4: 1/1
fps: 6.6702
1_DSiam, 3_david: 1/1
fps: 7.7331
1_DSiam, 4_david2: 1/1
fps: 7.7081
1_DSiam, 5_sylvester: 1/1
fps: 7.6745
1_DSiam, 6_trellis: 1/1
fps: 7.9951
1_DSiam, 7_fish: 1/1
fps: 7.1014
1_DSiam, 8_mhyang: 1/1
fps: 7.0084
1_DSiam, 9_soccer: 1/1
fps: 7.8004
1_DSiam, 10_matrix: 1/1
fps: 9.6954
1_DSiam, 11_ironman: 1/1
fps: 7.2538
1_DSiam, 12_deer: 1/1
fps: 7.0866
1_DSiam, 13_skating1: 1/1
fps: 8.0077
1_DSiam, 14_shaking: 1/1
fps: 7.3934
1_DSiam, 15_singer1: 1/1
fps: 6.4595
1_DSiam, 16_singer2: 1/1
fps: 7.0466
1_DSiam, 17_coke: 1/1
fps: 7.9295
1_DSiam, 18_bolt: 1/1
fps: 6.1423
1_DSiam, 19_boy: 1/1
fps: 7.4108
1_DSiam, 20_dudek: 1/1
fps: 5.213
1_DSiam, 21_crossing: 1/1
fps: 7.4788
1_DSiam, 22_couple: 1/1
fps: 8.0251
1_DSiam, 23_football1: 1/1
fps: 9.3892
1_DSiam, 24_jogging-1: 1/1
fps: 7.3301
1_DSiam, 25_jogging-2: 1/1
fps: 7.6771
1_DSiam, 26_doll: 1/1
fps: 7.2813
1_DSiam, 27_girl: 1/1
fps: 7.0408
1_DSiam, 28_walking2: 1/1
fps: 7.7656
1_DSiam, 29_walking: 1/1
fps: 7.469
1_DSiam, 30_fleetface: 1/1
fps: 5.5152
1_DSiam, 31_freeman1: 1/1
fps: 7.8266
1_DSiam, 32_freeman3: 1/1
fps: 7.327
1_DSiam, 33_freeman4: 1/1
fps: 8.4754
1_DSiam, 34_david3: 1/1
fps: 8.1489
1_DSiam, 35_jumping: 1/1
fps: 8.9554
1_DSiam, 36_carScale: 1/1
fps: 7.851
1_DSiam, 37_skiing: 1/1
fps: 7.0917
1_DSiam, 38_dog1: 1/1
fps: 7.5697
1_DSiam, 39_suv: 1/1
fps: 7.2588
1_DSiam, 40_motorRolling: 1/1
fps: 5.634
1_DSiam, 41_mountainBike: 1/1
fps: 9.3617
1_DSiam, 42_lemming: 1/1
fps: 6.2395
1_DSiam, 43_liquor: 1/1

**Comment by tsingqguo** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
Hi, thanks for interesting our work. Some factors should be considered for evaluation speed.1. the 40+fps is for using single CNN feature not the mulit-one.2. this version is wrapped into sub-functions and contains some repetition computation. 3. In our experiments, we find the matlab version affects the speed. We recommend Matlab 2015 or higher version.  Best,Qing Guo



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    




    On 04/14/2018 17:32，zhenxian zheng<notifications@github.com> wrote： 


Thanks for your sharing code, I run your code using my GPU 'TITAN TI 1080' , but I find that the speed is quite slow, and your paper introduce that the speed >40 fps. I also set the param useGPU = true. Could you please tell how to solve the problem?  Many thanks!
1_DSiam, 1_carDark: 1/1
fps: 7.4509
1_DSiam, 2_car4: 1/1
fps: 6.6702
1_DSiam, 3_david: 1/1
fps: 7.7331
1_DSiam, 4_david2: 1/1
fps: 7.7081
1_DSiam, 5_sylvester: 1/1
fps: 7.6745
1_DSiam, 6_trellis: 1/1
fps: 7.9951
1_DSiam, 7_fish: 1/1
fps: 7.1014
1_DSiam, 8_mhyang: 1/1
fps: 7.0084
1_DSiam, 9_soccer: 1/1
fps: 7.8004
1_DSiam, 10_matrix: 1/1
fps: 9.6954
1_DSiam, 11_ironman: 1/1
fps: 7.2538
1_DSiam, 12_deer: 1/1
fps: 7.0866
1_DSiam, 13_skating1: 1/1
fps: 8.0077
1_DSiam, 14_shaking: 1/1
fps: 7.3934
1_DSiam, 15_singer1: 1/1
fps: 6.4595
1_DSiam, 16_singer2: 1/1
fps: 7.0466
1_DSiam, 17_coke: 1/1
fps: 7.9295
1_DSiam, 18_bolt: 1/1
fps: 6.1423
1_DSiam, 19_boy: 1/1
fps: 7.4108
1_DSiam, 20_dudek: 1/1
fps: 5.213
1_DSiam, 21_crossing: 1/1
fps: 7.4788
1_DSiam, 22_couple: 1/1
fps: 8.0251
1_DSiam, 23_football1: 1/1
fps: 9.3892
1_DSiam, 24_jogging-1: 1/1
fps: 7.3301
1_DSiam, 25_jogging-2: 1/1
fps: 7.6771
1_DSiam, 26_doll: 1/1
fps: 7.2813
1_DSiam, 27_girl: 1/1
fps: 7.0408
1_DSiam, 28_walking2: 1/1
fps: 7.7656
1_DSiam, 29_walking: 1/1
fps: 7.469
1_DSiam, 30_fleetface: 1/1
fps: 5.5152
1_DSiam, 31_freeman1: 1/1
fps: 7.8266
1_DSiam, 32_freeman3: 1/1
fps: 7.327
1_DSiam, 33_freeman4: 1/1
fps: 8.4754
1_DSiam, 34_david3: 1/1
fps: 8.1489
1_DSiam, 35_jumping: 1/1
fps: 8.9554
1_DSiam, 36_carScale: 1/1
fps: 7.851
1_DSiam, 37_skiing: 1/1
fps: 7.0917
1_DSiam, 38_dog1: 1/1
fps: 7.5697
1_DSiam, 39_suv: 1/1
fps: 7.2588
1_DSiam, 40_motorRolling: 1/1
fps: 5.634
1_DSiam, 41_mountainBike: 1/1
fps: 9.3617
1_DSiam, 42_lemming: 1/1
fps: 6.2395
1_DSiam, 43_liquor: 1/1

**Comment by zhengzhenxian** [comment]
Many thanks  for your reply. My previous matlab version is 2014b, and I use 2016b now. As you suggest, my speed is faster than before. fps: 14.9072
1_DSiam, 47_basketball: 1/1
fps: 16.1925
1_DSiam, 48_football: 1/1
fps: 13.7846
1_DSiam, 49_subway: 1/1
fps: 15.3381
1_DSiam, 50_tiger1: 1/1
fps: 14.5511
1_DSiam, 51_tiger2: 1/1
fps: 14.7485
4/16 10:45:43

Besides, I run the dataset 'CVPR2013' today, i find that my auc score is just 0.612. I set the param netname = 'siamfc' and  nettype = '0res', which is not matching your score. Is there any problem with my params?
