### ISSUE TITLE
Requesting for raw results

### ISSUE THREAD

**Issue by willtwr** [tsingqguo/DSiam#4]
Hi,

Thanks for sharing your interesting work.
Is it possible for you to share raw results for your work as well?

Regards,
William

**Comment by tsingqguo** [comment]
Hi, William

Thanks for interesting our work. Please find the raw results on website:
https://tsingqguo.github.io/files/OTB-100.zip

Qing Guo




发件人：willtwr <notifications@github.com>
发送时间：2018-09-25 10:12
主题：[tsingqguo/DSiam] Requesting for raw results (#4)
收件人："tsingqguo/DSiam"<DSiam@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

Hi,
Thanks for sharing your interesting work.
Is it possible for you to share raw results for your work as well?
Regards,
William

**Comment by willtwr** [comment]
Hi Qing Guo,

Thank you very much for quick reply.
It would be much appreciated if you can provide the raw results for DSiam (without multi-layer fusion), too.

Sincerely,
William
